apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-ip
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /update-ip.sh
            envFrom:
            - configMapRef:
                name: azdnszone-config
            image: asksven/az-cli:2
            imagePullPolicy: IfNotPresent
            name: azdnszone
            resources: {}
            volumeMounts:
            - mountPath: /update-ip.sh
              name: batch
              subPath: update-ip.sh
          restartPolicy: Never
          volumes:
          - configMap:
              defaultMode: 511
              name: batch-config
            name: batch
  schedule: '* * * * *'
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 1
  suspend: false
